[package]
name = "blockchain-rocksdb"
description = "RocksDB backend for blockchain"
license = "GPL-3.0"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
blockchain = "0.8"
rocksdb = "0.12"
parity-codec = { version = "3.0", features = ["derive"] }
