[package]
name = "shuffling"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>", "Parity Team <admin@parity.io>"]
license-file = "LICENSE"

[dependencies]
blake2 = "0.7"

[features]
default = ["std"]
std = []
