[package]
name = "ssz-merkle"
version = "0.1.0"
authors = ["Parity Team <admin@parity.io>"]
description = "Merkle support for ssz."
edition = "2018"

[dependencies]
bm = "0.1"
digest = "0.8"
generic-array = "0.12"
ssz = { version = "0.1", path = "../ssz", default-features = false }

[features]
default = ["std"]
std = [
	"ssz/std",
]
